apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: ${{ values.cluster_name }}
  namespace: clusters
spec:
  autoscaling: {}
  controllerAvailabilityPolicy: SingleReplica
  dns:
    baseDomain: apps.eco-engineering.lab.eng.tlv2.redhat.com
  etcd:
    managed:
      storage:
        persistentVolume:
          size: 4Gi
        type: PersistentVolume
    managementType: Managed
  fips: false
  infraID: ${{ values.cluster_name }}
  issuerURL: https://kubernetes.default.svc
  networking:
    clusterNetwork:
      - cidr: 10.132.0.0/14
    machineNetwork:
      - cidr: 10.0.0.0/16
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: 172.31.0.0/16
  platform:
    kubevirt:
      baseDomainPassthrough: true
      generateID: ${{ values.cluster_name }}
      storageDriver:
        manual:
          storageClassMapping:
            - guestStorageClassName: ocs-storagecluster-ceph-rbd-virtualization
              infraStorageClassName: ocs-storagecluster-ceph-rbd-virtualization
        type: Default
    type: KubeVirt
  pullSecret:
    name: gitops-pullsecret
  release:
    image: quay.io/openshift-release-dev/ocp-release:${{ values.openshift_version }}-multi
  sshKey:
    name: sshkey-cluster-${{ values.cluster_name }}
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: Route
    - service: Konnectivity
      servicePublishingStrategy:
        type: Route
    - service: Ignition
      servicePublishingStrategy:
        type: Route
